// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "string",
    "version": "1"
  },
  "paths": {
    "/user": {
      "get": {
        "summary": "get",
        "description": "",
        "tags": [
          "User"
        ],
        "operationId": "get.get.user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "authorization",
            "required": true,
            "type": "string",
            "description": "Bearer ....."
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/UserProfileResponseDTO"
            }
          },
          "400": {
            "description": "Invalid authentication",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/user/register": {
      "post": {
        "summary": "register",
        "description": "",
        "tags": [
          "User"
        ],
        "operationId": "register.post.user/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterUserDTO"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "400": {
            "description": "Invalid authentication data",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "login",
        "description": "",
        "tags": [
          "Auth"
        ],
        "operationId": "login.post.auth/login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginUserDTO"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LoginResponseDTO"
            }
          },
          "400": {
            "description": "Invalid authentication data",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/auth/forgot-password": {
      "post": {
        "summary": "forgotpassword",
        "description": "",
        "tags": [
          "Auth"
        ],
        "operationId": "forgotpassword.post.auth/forgot-password",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ForgotPasswordDTO"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "400": {
            "description": "Invalid authentication data",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "summary": "resetpassword",
        "description": "",
        "tags": [
          "Auth"
        ],
        "operationId": "resetpassword.post.auth/reset-password",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ResetPasswordDTO"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "400": {
            "description": "Invalid authentication data",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/auth/change-password": {
      "post": {
        "summary": "changepassword",
        "description": "",
        "tags": [
          "Auth"
        ],
        "operationId": "changepassword.post.auth/change-password",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ChangeUserPasswordDTO"
            }
          },
          {
            "in": "header",
            "name": "authorization",
            "required": true,
            "type": "string",
            "description": "Bearer ....."
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "400": {
            "description": "Invalid authentication",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/user/update-profile": {
      "patch": {
        "summary": "updateprofile",
        "description": "",
        "tags": [
          "User"
        ],
        "operationId": "updateprofile.patch.user/update-profile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserDTO"
            }
          },
          {
            "in": "header",
            "name": "authorization",
            "required": true,
            "type": "string",
            "description": "Bearer ....."
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "400": {
            "description": "Invalid authentication",
            "schema": {
              "$ref": "#/definitions/GenericResponseVO"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    }
  },
  "definitions": {
    "RegisterUserDTO": {
      "properties": {
        "firstname": {
          "title": "RegisterUserDTO.firstname",
          "type": "string"
        },
        "lastname": {
          "title": "RegisterUserDTO.lastname",
          "type": "string"
        },
        "email": {
          "title": "RegisterUserDTO.email",
          "type": "string"
        },
        "telephone": {
          "title": "RegisterUserDTO.telephone",
          "type": "string"
        },
        "password": {
          "title": "RegisterUserDTO.password",
          "type": "string"
        }
      },
      "required": [
        "firstname",
        "lastname"
      ],
      "additionalProperties": false,
      "title": "RegisterUserDTO",
      "type": "object"
    },
    "UpdateUserDTO": {
      "properties": {
        "firstname": {
          "title": "UpdateUserDTO.firstname",
          "type": "string"
        },
        "lastname": {
          "title": "UpdateUserDTO.lastname",
          "type": "string"
        },
        "email": {
          "title": "UpdateUserDTO.email",
          "type": "string"
        },
        "telephone": {
          "title": "UpdateUserDTO.telephone",
          "type": "string"
        }
      },
      "required": [
        "firstname",
        "lastname"
      ],
      "additionalProperties": false,
      "title": "UpdateUserDTO",
      "type": "object"
    },
    "LoginUserDTO": {
      "properties": {
        "loginId": {
          "title": "LoginUserDTO.loginId",
          "type": "string"
        },
        "password": {
          "title": "LoginUserDTO.password",
          "type": "string"
        }
      },
      "required": [
        "loginId",
        "password"
      ],
      "additionalProperties": false,
      "title": "LoginUserDTO",
      "type": "object"
    },
    "GenericResponseVO": {
      "properties": {
        "statusCode": {
          "title": "GenericResponseVO.statusCode",
          "type": "number"
        },
        "body": {
          "title": "GenericResponseVO.body",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "body"
      ],
      "additionalProperties": false,
      "title": "GenericResponseVO",
      "type": "object"
    },
    "LoginResponseDTO": {
      "properties": {
        "code": {
          "title": "LoginResponseDTO.code",
          "type": "number"
        },
        "message": {
          "title": "LoginResponseDTO.message",
          "type": "string"
        },
        "data": {
          "properties": {
            "token": {
              "title": "LoginResponseDTO.data.token",
              "type": "string"
            }
          },
          "required": [
            "token"
          ],
          "additionalProperties": false,
          "title": "LoginResponseDTO.data",
          "type": "object"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "additionalProperties": false,
      "title": "LoginResponseDTO",
      "type": "object"
    },
    "ResetPasswordDTO": {
      "properties": {
        "loginId": {
          "title": "ResetPasswordDTO.loginId",
          "type": "string"
        },
        "token": {
          "title": "ResetPasswordDTO.token",
          "type": "string"
        },
        "password": {
          "title": "ResetPasswordDTO.password",
          "type": "string"
        }
      },
      "required": [
        "loginId",
        "token",
        "password"
      ],
      "additionalProperties": false,
      "title": "ResetPasswordDTO",
      "type": "object"
    },
    "ForgotPasswordDTO": {
      "properties": {
        "loginId": {
          "title": "ForgotPasswordDTO.loginId",
          "type": "string"
        }
      },
      "required": [
        "loginId"
      ],
      "additionalProperties": false,
      "title": "ForgotPasswordDTO",
      "type": "object"
    },
    "ChangeUserPasswordDTO": {
      "properties": {
        "oldPassword": {
          "title": "ChangeUserPasswordDTO.oldPassword",
          "type": "string"
        },
        "newPassword": {
          "title": "ChangeUserPasswordDTO.newPassword",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "ChangeUserPasswordDTO",
      "type": "object"
    },
    "UserProfileResponseDTO": {
      "properties": {
        "code": {
          "title": "UserProfileResponseDTO.code",
          "type": "number"
        },
        "message": {
          "title": "UserProfileResponseDTO.message",
          "type": "string"
        },
        "data": {
          "properties": {
            "firstname": {
              "title": "UserProfileResponseDTO.data.firstname",
              "type": "string"
            },
            "lastname": {
              "title": "UserProfileResponseDTO.data.lastname",
              "type": "string"
            },
            "email": {
              "title": "UserProfileResponseDTO.data.email",
              "type": "string"
            },
            "telephone": {
              "title": "UserProfileResponseDTO.data.telephone",
              "type": "string"
            }
          },
          "required": [
            "firstname",
            "lastname"
          ],
          "additionalProperties": false,
          "title": "UserProfileResponseDTO.data",
          "type": "object"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "additionalProperties": false,
      "title": "UserProfileResponseDTO",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http",
    "https"
  ]
};